### ISSUE TITLE
clarify instructions for building/installing makeme on windows

### ISSUE THREAD

**Issue by buzz3791** [embedthis/makeme#100]
The current build instructions at both [1] and [2] direct the user to build makeme with the command "make boot".  But on Windows, this fails:
```
c:\makeme-1.0.4>make boot

c:\makeme-1.0.4>projects\windows x64 nmake -f projects/makeme-windows-default.nmake boot

Using Visual Studio  (v16.0) from C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\

nmake -f projects/makeme-windows-default.nmake boot

Microsoft (R) Program Maintenance Utility Version 14.29.30140.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1073: don't know how to make 'boot'
Stop.

c:\makeme-1.0.4>
```

As far as I can tell, on Windows the correct build command is simply "make".  And the install instructions after build are just to add the makeme "bin" folder to the PATH system environment variable.

Please update README.md and installing.html to accurately document the build and install instructions for Windows.

1 - https://github.com/embedthis/makeme/blob/master/README.md
2 - https://www.embedthis.com/makeme/doc/start/installing.html

**Comment by mobsense** [comment]
Thanks -- fixed.
