### ISSUE TITLE
me not executable by others

### ISSUE THREAD

**Issue by wimpunk** [embedthis/makeme#52]
Just installed the latest version from git and noticed it was only executable by group and user, not by others.  Is this intentionally?

**Comment by wimpunk** [comment]
Addition: it seems like it gave the wrong permission to all the files installed.

**Comment by embedthis** [comment]
How did you install?  It should be 755.

More details please. Can you describe how you built, and installed. Then give an 

ls -l /usr/local/lib/makeme/latest

**Comment by wimpunk** [comment]
I've installed it like instructed, it thought it was something like `make && sudo make install`.  It could be related to the fact that I've cloned it on my mac and built it on a linux virtualbox with the filesystem mounted vbox.  I've fixed the contents to get it working so the contents of `ls -l /usr/local/lib/makeme/latest` probably isn't the contents as it was original.

```
$ ls -l /usr/local/lib/makeme/latest
lrwxrwxrwx 1 root staff 5 Jul  3 16:08 /usr/local/lib/makeme/latest -> 0.9.1
```

Maybe the contents could be more usefull:

```
$ ls -l /usr/local/lib/makeme/latest/
total 12
drwxr-sr-x 3 root staff 4096 Jul  3 16:08 bin
drwxr-sr-x 3 root staff 4096 Jul  3 16:08 doc
drwxr-sr-x 2 root staff 4096 Jul  3 16:08 inc
```

I hope this is enough info to help me.

**Comment by embedthis** [comment]
Must be due to how you have mounted the virtual box. We've not seen this before.

If you have it running by doing manual chmod, then that is fine.
