### ISSUE TITLE
issue in compiling the appweb for MIPS platform

### ISSUE THREAD

**Issue by pratappulugoru** [embedthis/makeme#90]
Dear Support team,

               I am working on porting the appweb server into the MIPS based embedded platform. The compiler details are as below
Compiler : mipsel-linux-uclibc-gcc

we have given the following command to cross compile the appweb server with MIPS platfom
./configure --platform linux-mips-debug
Then we observed that linux-mips-debug folder was created in Build folder of appweb. After that we have the following command
me install
then .so files are created in /linux-mips-debug/bin.  But we noticed that these .so files are created with x86 processor not for MIPS .Please let me know how to compile the appweb  for MIPS platform. Do i missed anything here.
With Regards
Pratap

**Comment by lranders** [comment]
Like you, I am also trying to cross compile a specific platform and I am struggeling with trying to figure out where to declare the CC and AR variables for it.

It would be great to see a working example of an appweb.me file where this is demonstrated...

**Comment by mobrien** [comment]
If you want to build for a cross platform target, you specify a 

--platform

./configure --platform linux-arm-debug

If you specify multiple platforms, they will be built for:

./configure --platform macosx-x86-debug --platform macosx-x64-debug

This will build x86 and x64 on mac.

You can specify --with and --without options to tailor the configuration PRIOR to the --platform option.

So to build for mips and local (on an x64 system) for linux:

./configure --platform linux-mips-debug --platform linux-x64-debug

To set the path to your compiler, set CC and CFLAGS:

CC=/usr/bin/arm-gcc ./configure.....

You can also use the --nocross or --nolocal options to "me" to suppress the local or cross builds.
