### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by svnpenn** [embedthis/makeme#92]
please and thank you

**Comment by mobrien** [comment]
Do you mean a binary build?

Because you can build using the projects -- either nmake or VS project.

**Comment by svnpenn** [comment]
@mobrien where is makeme.exe

**Comment by svnpenn** [comment]
@mobrien why was this closed - where is link to binary download

**Comment by mobrien** [comment]
Sorry, we closed due to question asked on Dec 23 that was unanswered. Thought this was an abandoned question.

We don't provide binary downloads. We provide source. MakeMe can be built from source using nmake or the VS project.

**Comment by svnpenn** [comment]
@mobrien you could grow your userbase if you provide such things. Its not to say that you need a build for every commit - but at least once a year

**Comment by mobrien** [comment]
Thanks for the encouragement. I'll make sure your voice is heard when we discuss this.
