### ISSUE TITLE
make boot on macos 10.14.5

### ISSUE THREAD

**Issue by toohamster** [embedthis/makeme#96]
Command failure: dyld: Library not loaded: @rpath/libejs.dylib
  Referenced from: /Users/myxdfhd/Downloads/sourcesApp/makeme-1.0.2/build/macosx-x64-release/bin/makeme-ejsc
  Reason: image not found

me: ERROR: Building target ejs.mod
Exiting

**Comment by dev-embedthis** [comment]
More details please. Did you build the software or is this the binary download.

Please provide full details of what you are doing.

**Comment by toohamster** [comment]
when I run make command.  it occur it error:


but today I run success,It's incredible.I haven't changed anything.
