### ISSUE TITLE
C++ Support?

### ISSUE THREAD

**Issue by MCOfficer** [embedthis/makeme#98]
I'm surprised that i didn't find any word on this in the docs, so here we go:

**Is MakeMe intended to be used as buildtool for C++?** If yes, how should one use it? The default compiler is gcc, and i see no way to change it.

**Comment by dev-embedthis** [comment]
Look at /usr/local/lib/makeme/latest/paks/me-os

The linux.me and gcc.me provide rule templates. You just need to add to gcc.me the extension transition for your compiler. Let us know what you need to add and we can add to the default rule set.

**Comment by MCOfficer** [comment]
From my vague understanding, the rule is actually there:

```
'cpp->o': '${targets.compiler.path} -c -o ${OUTPUT} ${MTUNE} ${CFLAGS} ${DEFINES} ${INCLUDES} ${PREPROCESS} ${INPUT}',
```

I was looking to compile `.cpp` files using g++.

**Comment by dev-embedthis** [comment]
Just change the ${targets.compiler.path} to whatever you want it to be.

That rule is a command template.

**Comment by MCOfficer** [comment]
Nice, that works.
```
    targets: {
        compiler: {
            path: '/usr/bin/g++'
        },
```

However, i feel like it would better to leave that to all the discovery methods in `compiler.me`, instead of hardcoding it.

To clarify, when you prompt me to change things, i'm not quite sure if i should edit my own start.me or edit makeme's files.
